[package]
name = "ProjetHW"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.3"

[profile.release]
panic = "abort"

[features]
arduino = []
teensy = []

[build]
target = "avr-unknown-gnu-atmega328" 
target2 = "thumbv7m-none-eabi"